import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'
import GamingServices from '@/components/GamingServices'
import TrendingTournaments from '@/components/TrendingTournaments'
import TrendingOrganisers from '@/components/TrendingOrganisers'
import LocalBusinesses from '@/components/LocalBusinesses'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <Navbar/>
        <GamingServices/>
        <LocalBusinesses/>
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-1'>
          <TrendingTournaments/>
          <TrendingOrganisers/>
        </div>
      </main>
       </>
  );
}
