import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'
import GamingServices from '@/pages/GamingServices'
import TrendingTournaments from '@/pages/TrendingTournaments'
import TrendingOrganisers from '@/pages/TrendingOrganisers'
import LocalBusinesses from '@/pages/LocalBusinesses'
import Link from 'next/link'
import teams from './teams'

const inter = Inter({ subsets: ['latin'] })
import image from 'next/image'
import LatestNews from '@/pages/LatestNews'
export default function Home() {
  return (
    <>
    <div>
         <image1
    src='/'
    alt='background image'
   />
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
 
      </Head>
      <div className={styles.container}>
   
        <GamingServices/>
        <LocalBusinesses/>
        <TrendingTournaments/>
       <TrendingOrganisers/>
       <LatestNews/>
      </div>
        
        <div className=''>
<teams/>
        </div>
        <div>
      
        </div>
      </div>
       </>
  );
}
